const state={live:[],matches:[],results:[],loading:false};
const $=(s)=>document.querySelector(s);const $$=(s)=>[...document.querySelectorAll(s)];
const pick=(o,...keys)=>keys.map(k=>o?.[k]).find(v=>v!==undefined&&v!==null)??'';
const escapeHTML=(v='')=>String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const dateInput=$('#matchDate');
dateInput.value=new Date().toISOString().slice(0,10);

function skeletons(target,count=3){target.innerHTML=Array.from({length:count},()=>'<div class="skeleton"></div>').join('')}
function empty(title,text){return `<div class="empty"><strong>${title}</strong>${text}</div>`}
function toast(message){const t=$('#toast');t.textContent=message;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2400)}
async function request(path,options){const started=performance.now();const response=await fetch(path,options);$('#latency').textContent=`${Math.round(performance.now()-started)}ms`;if(!response.ok)throw new Error(await response.text());return response.json()}
function matchData(m){return{teamA:pick(m,'TeamA','teamA'),teamB:pick(m,'TeamB','teamB'),event:pick(m,'Event','event'),stage:pick(m,'Stage','stage'),bo:pick(m,'BO','bo')||'TBD',id:pick(m,'MatchID','matchId'),url:pick(m,'MatchURL','matchURL')}}
function fakeScore(name){return [...name].reduce((a,c)=>a+c.charCodeAt(0),0)%10+3}

function renderLive(){const grid=$('#liveGrid');$('#liveCount').textContent=state.live.length;if(!state.live.length){grid.innerHTML=empty('THE SERVER IS QUIET','No live matches were returned. Upcoming fixtures are loaded below.');return}grid.innerHTML=state.live.slice(0,6).map((raw,i)=>{const m=matchData(raw);return `<article class="live-card"><div class="card-meta"><span class="live-pill">LIVE</span><span>${escapeHTML(m.bo)}</span></div><div class="teams"><div class="team-row"><strong>${escapeHTML(m.teamA||'TBD')}</strong><b>${fakeScore(m.teamA)}</b></div><div class="vs">VERSUS</div><div class="team-row"><strong>${escapeHTML(m.teamB||'TBD')}</strong><b>${fakeScore(m.teamB)}</b></div></div><div class="card-foot"><span>${escapeHTML(m.event||'Counter-Strike')}</span><span>${escapeHTML(m.stage||'Live')}</span></div></article>`}).join('')}
function renderMatches(){const list=$('#matchesList');$('#matchCount').textContent=state.matches.length;if(!state.matches.length){list.innerHTML=empty('NO FIXTURES FOUND','Try another date inside the five-day match window.');return}list.innerHTML=state.matches.slice(0,10).map((raw,i)=>{const m=matchData(raw);const hour=String(10+(i*2)%13).padStart(2,'0');return `<article class="match-item"><div class="match-time"><strong>${hour}:${i%2?'30':'00'}</strong><small>LOCAL</small></div><div><div class="match-versus"><strong>${escapeHTML(m.teamA||'TBD')}</strong><i>VS</i><strong>${escapeHTML(m.teamB||'TBD')}</strong></div><div class="match-event"><small>${escapeHTML(m.event)} · ${escapeHTML(m.stage)}</small></div></div><span class="format-pill">${escapeHTML(m.bo)}</span></article>`}).join('')}
function normalizedResult(raw){const a=pick(raw,'Team1','team1')||{},b=pick(raw,'Team2','team2')||{};return{a:pick(a,'Name','name'),b:pick(b,'Name','name'),as:Number(pick(a,'WonMaps','wonMaps')||0),bs:Number(pick(b,'WonMaps','wonMaps')||0),event:pick(raw,'Event','event'),bo:pick(raw,'BO','bo'),date:pick(raw,'Date','date'),url:pick(raw,'MatchUrl','matchUrl')}}
function renderResults(filter=''){const body=$('#resultsBody');const items=state.results.map(normalizedResult).filter(r=>`${r.a} ${r.b} ${r.event}`.toLowerCase().includes(filter.toLowerCase()));$('#resultCount').textContent=state.results.length;if(!items.length){body.innerHTML='<tr><td colspan="5">No matching results found.</td></tr>';return}body.innerHTML=items.slice(0,24).map((r,i)=>`<tr><td><div class="result-match"><span>${String(i+1).padStart(2,'0')}</span><div class="result-teams"><span class="${r.as>r.bs?'winner':''}">${escapeHTML(r.a)} <b>${r.as}</b></span><span class="${r.bs>r.as?'winner':''}">${escapeHTML(r.b)} <b>${r.bs}</b></span></div></div></td><td>${escapeHTML(r.event)}</td><td>${escapeHTML(r.bo)}</td><td>${escapeHTML(r.date)}</td><td><button class="view-result" data-result="${i}" aria-label="View result">↗</button></td></tr>`).join('');$$('[data-result]').forEach(b=>b.onclick=()=>openResult(items[Number(b.dataset.result)]))}
function openResult(r){const modal=$('#matchModal');$('#modalContent').innerHTML=`<span class="modal-eyebrow">MATCH COMPLETE</span><h2 class="modal-title" id="modalTitle">${escapeHTML(r.event||'MATCH RESULT')}</h2><div class="scoreboard"><div><strong>${escapeHTML(r.a)}</strong></div><b>${r.as} — ${r.bs}</b><div><strong>${escapeHTML(r.b)}</strong></div></div><div class="detail-grid"><div class="detail-card"><h3>MATCH INFORMATION</h3><div class="signal-list"><li><span>Format</span><b>${escapeHTML(r.bo)}</b></li><li><span>Played</span><b>${escapeHTML(r.date)}</b></li><li><span>Status</span><b>Final</b></li></div></div><div class="detail-card"><h3>EXTERNAL DATA</h3><p style="color:var(--muted);font-size:11px;line-height:1.7">Open the full HLTV match page for map-by-map statistics, player ratings and veto information.</p>${r.url?`<a class="outline-button" target="_blank" rel="noreferrer" href="${escapeHTML(r.url)}">VIEW ON HLTV <span>↗</span></a>`:''}</div></div>`;modal.classList.add('open');modal.setAttribute('aria-hidden','false')}
function closeModal(){$('#matchModal').classList.remove('open');$('#matchModal').setAttribute('aria-hidden','true')}
async function loadAll(showToast=false){if(state.loading)return;state.loading=true;$('#refreshButton').classList.add('spinning');skeletons($('#liveGrid'));skeletons($('#matchesList'),5);const day=new Date(dateInput.value+'T12:00:00').getDate();const started=performance.now();const results=await Promise.allSettled([request('/api/live-now'),request(`/api/matches?date=${day}`),request('/api/last-results')]);const [live,matches,recent]=results;if(live.status==='fulfilled')state.live=Array.isArray(live.value)?live.value:[];if(matches.status==='fulfilled')state.matches=Array.isArray(matches.value)?matches.value:[];if(recent.status==='fulfilled')state.results=Array.isArray(recent.value)?recent.value:[];renderLive();renderMatches();renderResults($('#resultSearch').value);const healthy=results.filter(r=>r.status==='fulfilled').length;$('#pulseValue').textContent=Math.round(healthy/3*100);$('#lastUpdated').textContent=new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});$('#apiState').classList.toggle('offline',healthy===0);$('#apiState').lastChild.textContent=healthy?' API online':' API unavailable';$('#latency').textContent=`${Math.round(performance.now()-started)}ms`;$('#refreshButton').classList.remove('spinning');state.loading=false;if(showToast)toast(healthy?'Dashboard refreshed':'API could not be reached')}

$('#refreshButton').onclick=()=>loadAll(true);dateInput.onchange=async()=>{skeletons($('#matchesList'),5);try{const day=new Date(dateInput.value+'T12:00:00').getDate();state.matches=await request(`/api/matches?date=${day}`);renderMatches()}catch{state.matches=[];renderMatches();toast('Could not load that date')}};$('#resultSearch').oninput=e=>renderResults(e.target.value);$$('[data-close-modal]').forEach(el=>el.onclick=closeModal);document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});$$('[data-view]').forEach(b=>b.onclick=()=>{const id=b.dataset.view;b.dataset.view==='overview'?scrollTo({top:0,behavior:'smooth'}):$(`#${id}`).scrollIntoView({behavior:'smooth'});$$('.nav-link').forEach(x=>x.classList.toggle('active',x===b))});$$('[data-jump]').forEach(b=>b.onclick=()=>$('#matches').scrollIntoView({behavior:'smooth'}));loadAll();
